### ISSUE TITLE
Review and improve repository subtitles 

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#1075]
During #987 @ainali and I realised that our repository subheadings could use a bit of attention. 

We felt that some had a nice indication of what to expect in the repositroy (eg About, governance-game, community-translated-standard). Others could be improved to provide the user a bit more description of what to find in the repository, who it is for, and so on, instead of a repetition of the title (eg standard, blog or projects).

Repositories we felt could be improved:
- [x] blog
- [x] standard
- [x] jitsi-community
- [x] illustrations (should this maybe be part of brand?)
- [x] publiccode.net
- [x] governance-game
- [x] projects
- [x] codebasestewards (could maybe be removed)
- [x] bumperscripter
- [x] playground 

Some items to consider when improving subheadings:

* what is in the repository?
* who is the repository for?
* what does it help do/what is it used for?

Small additional point - some have full stops some don't. 

Future work could include improving the naming of repositories, such as changing standard to standard-public-code. This would make the repositories easier to navigate after being forked.

**Comment by Ainali** [comment]
Suggestions:
* blog: Home to the Blog for Public Code and where blog posts are planned and collectively written.
* standard: The Standard for Public Code - a model for public organizations to build their own open source solutions to enable successful future reuse by similar public organizations in other places.
* jitsi-community: A tool that allows users to sign up to a Jitsi instance that is not open to everyone, using a web UI so that they can start sessions by themselves.
* illustrations: A collection of illustrations meant to be reused in the communications of the Foundation for Public Code.
* publiccode.net: The website of the Foundation for Public Code that is the most public facing and the primary place for people to learn about the organization.
* governance-game: Card game used to learn what needs of governance organizations collaborating on public code codebases has.
* projects: Home to a list of useful resources developed by the Foundation for Public Code.
* codebasestewards:  An issue-only repository, containing the issues codebase stewards are actively working on, that does not ft in other repositories. These are used on the weekly planning board.
* bumperscripter: Script to generate video podcast bumper animations using the Processing framework. Makes it easy to create animations where only a few text strings change every episode (like guest names etc.).
* playground: A repository for our staff to learn, play and experiment with git. Not meant for reuse.

**Comment by Ainali** [comment]
@clausmullie and I iterated on my first suggestion and they have been updated. I'll close this issue as I think this is resolved.

**Comment by clausmullie** [comment]
History of work at [#2](https://github.com/publiccodenet/.github/pull/2)
