### ISSUE TITLE
Metrics: Where do we store our different success metrics?

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#219]
## Where do we store our different success metrics?

In pull request #215 we included a file on success of code base stewardship. In this review @bvhme suggested having a generic metrics.md https://github.com/publiccodenet/about/pull/215/files

As each of our activities will have their own success metrics (so stewardship has its own success, member relations its own success, communications idem) we should think about how to do this. Either we should a) centralize them in a root, b) have the content live in the branches, or c) have an index in the root that links to content living in branches. 

I currently feel for the latter. 

@ElenaFdR and @MirjamvT what's your opinion on this?

for our success metrics see #230

**Comment by bvhme** [comment]
I would say, store the metrics with the activities and they can.be
centralised by searching the entire repo for the metrics.md filename

**Comment by ElenaFdR** [comment]
Though it's straightforward to come up with success metrics for each activity, not all activities documented on About are equally important to the organization. Not every activity needs to be captured as part of the success metrics for org. If we put the success metrics in branches with an index, the index could provide context: which metrics matter the most, how often we do measurement, how we report on/publish our measurement.

**Comment by bvhme** [comment]
Although I believe that tracking the metrics is an activity in its own right the question here is whether the metrics make no sense with the activities.

Like the guides, I think it would make more sense for the metrics to live in the activity folder, close to all the other subject matter. Instead of removed from the context to the 'measure effectiveness' activity.

I would say, make measuring effectiveness a part of every activity instead of a separate activity.

Additionally, I feel more people might think about the metrics if they aren't in a specific another place. And, I think that by creating one folder or file for the metrics we also create one formula for them leading into one super-metric, reducing the ease to produce have multiple aggregate metrics.

**Comment by bvhme** [comment]
Also, as a general note @clausmullie, these are definitely two separate issues :)

**Comment by clausmullie** [comment]
@bvhme hehe agreed. fixed!

**Comment by ElenaFdR** [comment]
The success metric we're currently working with is [our milestones](https://about.publiccode.net/organization/milestones/).
