### ISSUE TITLE
Publish form for submitting expenses 

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#331]
As required by the remuneration policy.

**Comment by Ainali** [comment]
Since we are using Nmbers/Tentoo now, perhaps this is redundant and can be closed? Or is this for external persons?

**Comment by MirjamvT** [comment]
For external (and for Ben) it is still useful.

 

 

Best regards,

Mirjam van Tiel

 

Van: Jan Ainali <notifications@github.com> 
Verzonden: maandag 28 oktober 2019 15:55
Aan: publiccodenet/about <about@noreply.github.com>
CC: MirjamvT <mirjam@publiccode.net>; Assign <assign@noreply.github.com>
Onderwerp: Re: [publiccodenet/about] Publish form for submitting expenses (#331)

 

Since we are using Nmbers/Tentoo now, perhaps this is redundant and can be closed? Or is this for external persons?

**Comment by clausmullie** [comment]
@demkodo

**Comment by demkodo** [comment]
Hey guys, and is [this the form](https://docs.google.com/spreadsheets/d/1m_5vpScmpBAFOOXUEGWEqrd2FF_WhLjoJDcPF9wT_0Y/edit#gid=0) we are talking about?

**Comment by clausmullie** [comment]
I think so. This probably should go on the remuneration policy page?

**Comment by demkodo** [comment]
Yeah, can add a link to it - will do that now :)

**Comment by clausmullie** [comment]
Closed with #625
