### ISSUE TITLE
Create concise, friendly overview of how codebase stewardship works

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#341]
This should be a reusable asset that can be shared within member organizations.

It should be more accessible than the [BPMN codebase lifecycle diagram](https://about.publiccode.net/activities/codebase-stewardship/lifecycle.html).

**Comment by bvhme** [comment]
This can go into the `lifecycle.md` that now includes the BPMN since it is meant to be a place for more and clearer context.

**Comment by ericherman** [comment]
In order to concisely explain stewardship we need to have a shared understanding of stewardship. Additionally everything in the explainer should be found in the standard. What came to light was that community and marketing aspects of stewardship are missing from the standard and thus we need to expand the standard to include these missing bits.

**Comment by bvhme** [comment]
Yes. I don't think everything about how codebase stewardship works needs to
be in the standard, it should be in the activities section on this repo.
Only the standard we hold projects too should be in the standard with their
context. This so others can use the standard as a high water mark without
requiring certain ways of working around this.

**Comment by clausmullie** [comment]
See issue #428 for thinking around this, and pull requests #431, #519 & #613 for increments towards this.

**Comment by bvhme** [comment]
I'm closing this issue as I think it is too open and lacks the scope to be able to fix it. However a lot of work has been done for example in explaining codebase stewardship.
