### ISSUE TITLE
The license text in the footer should be a link to the license file

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#410]
In the Standard, the CC0 text in the footer is a link to the license file in the repo. But in About it is just plain text. Is that a bug when generating the pages?

**Comment by bvhme** [comment]
I've checked and this is because the `LICENSE` file isn't included in the render by default in Jekyll. In the other repo it is a Markdown file, in this one a text one.

To fix this we should rename the LICENSE to `LICENSE.md` (or copy it from the repo) and include `LICENSE.md` in the `include` list configuration in the `config.yml`.

The `include` from the `standard` repo `config.yml`:

```yaml
include:
  - "README.md"
  - "CONTRIBUTING.md"
  - "LICENSE.md"
  - "CODE_OF_CONDUCT.md"
```
