### ISSUE TITLE
Put presentations/slides on about?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#543]
I couldn't find any of the presentations that have been done by us on about. Perhaps we should add somewhere both the presentations that have been given and perhaps also a template slidedeck for a general presentation about the foundation and possibly specific ones about the standard and stewardship?

**Comment by ElenaFdR** [comment]
They're not published for 2 reasons:
1. So that the content is new to the audience when we present it.
2. The slides don't have speaker notes, and aren't designed to be self-explanatory on their own. [This blogpost argues for why you shouldn't share slides](https://gds.blog.gov.uk/2016/05/10/doing-the-hard-work-to-make-talks-readable/).

I have no objections to publishing the slides for presentations that are already in the public domain (for example a blogpost with links to the slides and video for Ben's DecidimFest talk).

**Comment by Ainali** [comment]
My main reason for putting them there was not to share them with an outside audience, but to have them as a resource for employees of the Foundation. It should be easy for anyone here to find them as both inspiration for new presentations and as a historical reference of what we have used before. 

I agree that a blogpost after a presentation with a summary of key points is much better for an outside audience, but that doesn't contradict what I am aiming for. Since our ethos is to put anything on about that isn't explicitly secret, the question becomes, are they really secret?

**Comment by ElenaFdR** [comment]
Update: what about creating:

* activities/communications/giving-presentations
* activities/communications/past-talks

**Comment by bvhme** [comment]
I like the `activities/communications/giving-presentations`!

Perhaps the past talks should live on the Blog as they are 'ephemera'.

**Comment by Ainali** [comment]
Fixed by publiccodenet/projects#16  that created https://projects.publiccode.net/talks-and-articles.html
