### ISSUE TITLE
Setting up Discourse for ourselves

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#580]
This is a spin-off from #423. 
For our own communities we would like to setup a Discourse instance. (In #521 the domain for that is discussed.)
Suggestions for main categories to start with: Stewardship, Standard for Public Code and About us.

**Comment by fbartels** [comment]
It could be an idea to run Discourse on an instance of https://cloudron.io/. Cloudron is free for up to two apps (you just need a server) and there is a ready to use Discourse app for it already.

**Comment by demkodo** [comment]
We just 'spun' up at VPS at Maadix to run Discourse. Maadix is a really cool, independent service provider, and they take on the most difficult part of managing the servers, something we would otherwise need to do ourselves if we would use the services of Cloudron (although it looks awesome, thanks in any case for pointing us here). I'm a beginning system admin person so the Maadix solution is really great, as they offer open source software installation as Ansible recipes literally only need to click a bunch of buttons, making my life very easy :) https://maadix.net/
