### ISSUE TITLE
Update Membership Growth page

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#620]
On About > Activities
Update [Membership Growth](https://about.publiccode.net/activities/membership-growth/) page
- remove old links; add disclaimer to old links; move them to "Further reading" sections
- rewrite how to become a member Step 2
- update Further Reading links

**Comment by bvhme** [comment]
What are the old links? Also, I don't think 'further reading' should be a place to stash old shit. If we need to keep those things around we should also have a clear goal for them, otherwise it is too hard to understand what is current or outdated information. Also GitHub stores everything in history so we should not keep any outdated things around if they are needless, we can use the archive for reference.

**Comment by bvhme** [comment]
I didn't see #621 before this one, without that context I wrote the comment above.
