### ISSUE TITLE
Community assets for early incubation

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#627]
Similar to [Product assets for early incubation](https://about.publiccode.net/activities/codebase-stewardship/product-assets-for-early-incubation.html) it would be very useful to have a list for community assets. We should run a workshop like the one Elena did for product to both capture those assets that are most needed, and also get them in some prioritized order.

**Comment by lscheske** [comment]
I think this is a great idea - maybe it could just be "Assets for community building", since I think early incubation is more for the product itself. 

Like this we can have a workshop that captures assets that we find important for community building in general, and reflect the overarching and more specialized communities we build/are engaging.

**Comment by Ainali** [comment]
Calling it that makes sense. As you see from the product list (or perhaps the complete spreadsheet in our Drive), it is more or less complete, it's just the prioritized order that is special for early incubation.

**Comment by ElenaFdR** [comment]
NB: we also chose to only publish the first part of the list because our degree of confidence (re both sequence order and priority) decreased as a codebase became more mature.

**Comment by AlbaRoza** [comment]
Let's do it next week, shall we?

**Comment by Ainali** [comment]
Closed by #661
