### ISSUE TITLE
Lack of information sharing between teams

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#639]
Suggested solution: weekly public email with updates about everything that is done.

This will help with #632 as well.

**Comment by Ainali** [comment]
Is this an end of week report of what has happened, or start of week report describing what is planned (or a mix of both)?

**Comment by ericherman** [comment]
I expect that we'll fall into a mix of both, with more of which-ever seems most important. Laura's email I think serves as a top-shelf example: brief, but enough info to get a sense of what's going.

**Comment by AlbaRoza** [comment]
Agree with @ericherman. What about a weekly call in which each team briefly explains the rest what they've been working on?

**Comment by lscheske** [comment]
I agree with all of this! I think a weekstart meeting e.g. Monday morning would be great. Each team (Codebase, Membership, Communications) could have 5 minutes to briefly explain key achievements from the week prior, and main activities for the upcoming week. 

I will personally also keep sending notes from the (now bi-weekly) membership tactics meeting to everyone so that we have a written record of decisions.

**Comment by ElenaFdR** [comment]
We've implemented a weekly forward look meeting. The public expression of this is a monthly newsletter, captured in [publiccode.net issue 87)https://github.com/publiccodenet/publiccode.net/issues/87).
I'm going to close this issue now.
