### ISSUE TITLE
Create individual pages for each of the pillars

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#647]
We have come to a point when we are getting more and more resources like tools and templates created that it would be handy to be able to list and link them per each pillar. I suggest that we make the page for [codebase stewardship](https://about.publiccode.net/activities/codebase-stewardship/activities.html) only having the general content, and move the other ones to new sub pages that can host more pillar specific resources. This was suggested during today's Weekly stewards meeting.

**Comment by bvhme** [comment]
I understand that #649 doesn't really solve this issue in this way. I would however like to argue we should be putting these processes and resources directly under 'activities' so that we don't break up our organizational structure.

The `activities.md` file was always meant to serve the role you're describing in your issue, just decentralised, so perhaps we can resolve this issue there?
