### ISSUE TITLE
Splitwise in for-staff contributing guide

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#665]
Do we still use Splitwise?

@demkodo Should this be updated? Or am I forgetting something?

**Comment by ericherman** [comment]
We no longer use (nor need to use) Splitwise. There may be some unsettled balances and some unfiled entries, but we should remove it from the guide.

**Comment by demkodo** [comment]
Not at the moment but this might change if we move to a new office that doesn't have a bakery around the corner where we can buy on account instead of advancing it ourselves, so let's leave it. What I can do is add that we are currently not actively using it, but since a move is imminent it will be unhandy to add it again, right?

**Comment by bvhme** [comment]
I'd remove it and add it again later. Using the 'blame' and 'history' views in Git you can travel back in time to retrieve any old information so it doesn't have any value to have it around if we're not using it.
If we're not doing something it shouldn't be in our documentation.
