### ISSUE TITLE
Define "Partners" for internal purposes in the Glossary

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#687]
Derived from: #660 
Solves #499 

Proposed definition of **Partners** for the [glossary](https://about.publiccode.net/glossary):

Partners are organizations with whom we work closely together. They may include organizations that are on the path to become members, or organizations that are collaborating with us on a project. We do not have formal agreements with our partners, but ask for consent when using their names in our external communications.

**Comment by bvhme** [comment]
As I read this proposal I think it might be simplified to:

* Partners are those who we collaborate with.

Some questions/thoughts, on your proposal:

* Is close the limiting factor?
* Does 'other organizations' open this up to everyone?
* If so, what about individuals?
* The sentence of 'we do not have...' seems unnecessary, we should ask for permission if we don't have it and the beginning is sufficiently vague to not expect an agreement.
* We don't need to name them explicitly as partners in external communications, but can also use a more mutually agreeable term when opportune, right?

Also, I actually don't think this solves #499 since that points to partners as defined in our [documentation as 'vendors and the private sector'](https://about.publiccode.net/activities/value-and-impact/user-mapping/). This idea dates back to our initial proposal for the foundation where we used the term to mean 'implementer/tech/software developers/consultants...'. We don't need to be stuck to those, but they are a different issue.

This proposes a new definition of partners, replacing that one that we've used but not put in the glossary. So it does not solve #499, it just requires us to find a new term for this and replace those.

**Comment by lscheske** [comment]
A few more thoughts on this: 

* Close does not need to be the limiting factor, but the fact that we are actually working together on a project
* This definition opens it up to everybody we are working with on our codebase projects e.g. Dimpact/VNG/Utrecht/Den Haag)
* Agree to remove we do not have sentence on formal relations
* To solve #499, we could split the Partner group into Public and Private Partners, then we would have categories to mention stakeholders like Maykin Media, or other vendors & the private sector. 

Definitions could then be something like: 

Public partners: Public organizations with whom we work together on a project. They may be organizations that are on the path to become members.

Private partners: Private companies with whom we work together on a project. They may include vendors or the broader private sector.
