### ISSUE TITLE
Should "Affiliates" continue being formal relations?

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#689]
derived from #660 

An **affiliate** is currently defined as:
"A non-profit organization that has an aligned mission with us and we have formal relations with."  
in our [Glossary](https://about.publiccode.net/glossary/affiliate-definition.html) 

I propose an **editorial change** to this definition: 
"A non-profit organization whose mission aligns with ours ..."

And ask whether we want to continue having formal (affiliate agreements) with these, or whether we should make it less formal? 

Also, where is the template affiliate agreement? 

@clausmullie @bvhme @nebster

**Comment by bvhme** [comment]
Affiliate agreements have so far always been sent to us, we don't have a template, and I don't think we need one. Just mutual agreement is necessary. The 'formal relations' here is partly that it's public we talk to each other (we have each other's phone numbers and contact details) and acknowledged by both sides.

An example of an affiliate that might be useful for us: [OSI Affiliate](https://opensource.org/affiliates/about)

Since there is no working relationship necessary in an affiliate relationship I think some kind of formal (preferably public) acknowledgment seems necessary. For example: we can't just say the OSI is an affiliate of ours if they don't reflect that as well. Additionally, we can't tell the story of how we work together if there is little.

As a side note: I do think this could also include public organizations, not just non-profits.

What would the goal be of not having these relations be formal?

**Comment by lscheske** [comment]
Ah, in my world, what you describe is called an informal relationship i.e. relationships that follow some kind of informal agreement to work together (can be written). 

Formal agreements are typically signed documents like contracts.

**Comment by lscheske** [comment]
I also agree that we don't need one, in which case we should remove the "formal relations" parts from the definition, as this is misleading. If our Affiliate organisations send us an agreement on THEIR side, that part of their definition, and not ours, and we're likely happy to agree to that.

The OSI Affiliate Agreement is an example of an informal agreement (not legally binding).

**Comment by bvhme** [comment]
First of all I'm interested in the goal of removing the formal part. Because I don't know what we would then use this for.

The goal of 'affiliates' has in my view always been to have formal relationships. Meaning relationships that exist because they are mutually defined and not because they happen to be relationships.

This can for instance be:

* to publicly acknowledge you're aligned and not competing, or
* to show to your community you have access to their network and help if something happens, or
* as a sign of mutual support and create openings for collaboration.

This doesn't have to happen through a contract, both posting it on your blog can also be a way, or a simple agreement over email (which is as it happens also legally binding).

What is your plan for this term?

**Comment by lscheske** [comment]
Removing formal part: make it sound less bureaucratic, remove need to actually have a formal agreement template. 

I agree with doing all this without a contract, which is exactly why I would argue it is informal. 

The definition could then be something like "A non-profit organization whose mission aligns with ours, and has committed to publicly support our work (and vice-versa)" 

This removes any mention of any agreement, but still makes clear that there is commitment and mutual support.
