### ISSUE TITLE
Long sentence in definition of public code

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#723]
This paragraph long sentence from[ the glossary definition of public code](https://about.publiccode.net/glossary/public-code-definition.html) is a bit hard to parse:

> By developing public code independent from but implementable in a local context, as well as documenting the development process openly, it can provide a building block for others to re-implement in their local context, take as a starting point to continue development or as a basis for learning.

I suggest we make it easier to read by splitting up into several sentences. Suggestion:

> Public code can provide a building block for others to re-implement in their local context. It can serve as a starting point to continue development or as a basis for learning. To enable that, the development of public code needs to be independent from, but implementable in, a local context. The development process must also be documented openly.

**Comment by ericherman** [comment]
I like this.

Also, I suggest s/need/needs/ in "the development of public code need to be independent"

**Comment by lscheske** [comment]
I'm not sure the sentence logic makes sense - is it "public code" that provides a building block, or the fact that it is developed independently, documented, and openly? I think if we remove the word building block from Jan's version it would make more sense. 

The first sentence could then be: "Public Code can/should be built/designed in a way so that it is implementable in different contexts."  (not sure which words are better in some places, so left some options with /)

**Comment by Ainali** [comment]
> I'm not sure the sentence logic makes sense - is it "public code" that provides a building block, or the fact that it is developed independently, documented, and openly? I think if we remove the word building block from Jan's version it would make more sense.

Instead of removing building block, I think changing the word provide to be will give it sense. 

> Public code can be a building block for others to re-implement in their local context. ..

**Comment by lscheske** [comment]
That's already better, what is unclear in this entire definition is what it is a building block of.

**Comment by Ainali** [comment]
> That's already better, what is unclear in this entire definition is what it is a building block of.

That's a good point! How about this:

> Public code can be building blocks for others to re-use and re-implement in their local context, creating their public code. It can serve as a starting point to continue development or as a basis for learning. To enable that, the development of public code needs to be independent from, but implementable in, those contexts. The development process must also be openly documented.

So public code can be building blocks (of public code) to create new public code. Does that make sense?

**Comment by lscheske** [comment]
Full glossary entry:

Changes in italics

*Public code is open source software developed by public organizations, together with the policy and guidance needed for reuse. It encompasses* both civic code (like policy or regulation) and computer source code (such as software and algorithms) executed in a public context, by humans or machines. 

Because public code serves the public interest, it should be: open, legible, accountable, accessible and sustainable.

*It should be designed in a way so that it is implementable in different contexts, with open documentation of the development process. By doing this, public code building blocks can be re-used by others in their local contexts to create new public code.  It can serve as a starting point to continue development or as a basis for learning.*
> still struggling with this para.

To facilitate re-use, public code should be either released into the public domain or licensed with an open license that permits others to view and reuse the work freely and to produce derivative works.

**Comment by Ainali** [comment]
If we are changing more than just the single original long paragraph, we should probably incorporate language from [this change](https://github.com/publiccodenet/standard/pull/397/commits/0fa0d345e3321e69510376e0d8849cae050435a4) too where civic code was removed.
