### ISSUE TITLE
Guidance on what tools are required and what not

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#764]
Clarify our strategy on what tools are core for what everyone needs to use and what tools people can freely choose to use.

**Comment by bvhme** [comment]
Our required tools: `about` on GitHub, email, calendar, 1password and Tentoo

**Comment by ElenaFdR** [comment]
Optional tools: office, chat, video, hackMD, mailing lists. The definition of optional is that people can choose the tool of their choosing, or we can easily switch tools. 
(NB: the org may not decide to support all tools, or to offer more than 1 tool for a function).

What about dedicatng a mandatory for secret information? Or should all that just be in 1pw?

**Comment by Ainali** [comment]
Does Jitsi also qualify to these tools (since we are using it daily for our meetings). One employee cannot really choose to use another video system than all the others.

Email and calendar isn't so much a tool, but a type of tool. There are plenty of tools to choose from. So I guess or required tools really are Gmail and Google Calendar.

**Comment by bvhme** [comment]
To clarify what this mean is what we need to do. Required tools are the tools that we demand certain things are done on. Optional tools are tools that people can use to do their work, but also choose to use different ones whenether it's relevant to them.

For instance: you are required to use email to inform people you work with about things they need to know. In contrast, if you decide with everyone in the stewards call to use Meet over Jitsi, you are free to decide.
