### ISSUE TITLE
List of open source policies from governments (moved from publiccode.net repo)

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#793]
Relevant encouraging policy frameworks:
- About repo issue [716](https://github.com/publiccodenet/about/issues/716)
- About repo issue [630](https://github.com/publiccodenet/about/issues/630) and 
- About repo issue [572](https://github.com/publiccodenet/about/issues/572)) 

Users:
- general public
- awareness raising with the general public
- fan at public organizations (#71)

From: communications assets for membership workshop, 23 July 2020

**Comment by ElenaFdR** [comment]
Proposed home: https://about.publiccode.net/activities/value-and-impact/

Initially, this can pull together:

- #630 
- #572 
- Dutch policy: [April 2020 kamerbrief](https://www.rijksoverheid.nl/documenten/kamerstukken/2020/04/17/kamerbrief-inzake-vrijgeven-broncode-overheidssoftware)

**Comment by Ainali** [comment]
Wikidata recently created two properties to track exactly this:

- [FLOSS development policy URL](https://www.wikidata.org/wiki/Property:P9904)
- [open source software usage policy URL](https://www.wikidata.org/wiki/Property:P9771)

This means that they want to track this and would be happy if data for public organizations were added. For us, it means that we could either have a great source to pick from, or just point to them as the resource to look at. If we want to be really bold, we could even just embed the results from a [Wikidata query](https://w.wiki/48Ne) (if we can do it in Jekyll that is), but I think that may be taking it a bit too far, as it also includes policies of other organizations than public ones.

It also means that it would be uncontroversial for us to add any policies we find to the Wikidata items of their organizations (but we need of course to be transparent and declare it on our user page).

**Comment by Ainali** [comment]
After thinking a bit more about this, I think we should not try to collect an exhaustive list of policies. Instead, I would like to create a resource under Understanding our users (see [comment on 658](https://github.com/publiccodenet/about/issues/658#issuecomment-1017629738)) with typical examples that would help us emphatize with the people we work with. It could include an example or two of a law, policy decision, strategies etc, but explicitly not aim to be *the list*. If we find such lists elsewhere, they could instead be added as Further reading.

The reasoning behind this is that:
1) We do not need to collect an authoritative list on our marketing site because we are not a lobbying organization
2) We do not need to collect an authoritative list on our about, because we are not actively involved in policy making
3) We can however have a non-authoritative list as a resource for staff to both understand the (different) needs and thinking of governments, as well as share as best practice with our stakeholders

This avoids us having to 'collect them all', but instead focus our attention on adding only those best-in-class and that add value by illustrating a different approach or angle.
