### ISSUE TITLE
Switch markdown processor to kramdown

### ISSUE THREAD

**Issue by angelplasma** [publiccodenet/about#902]
**Idea**
Switch from Github's default markdown processor to **kramdown** (which is actually Jekyll's default processor).

**Goals**
- General: Extend publiccode.net's markdown capabilities
- Acute: Visually enhance the upcoming Annual Report, which we would like to keep in markdown (as opposed to full html)

**Ramifications**
- This should enable additional visual and structural sophistication for markdown pages, including additional html and css-based abilities.
- This should not change the appearance or structure of existing pages.

**More Info**
- https://jekyllrb.com/docs/configuration/markdown/
- https://github.com/gettalong/kramdown
- https://kramdown.gettalong.org/installation.html

**Comment by bvhme** [comment]
Hey @angelplasma, 

The history and perspective of this choice is because we assumed that using GitHub as a content management system would become significantly more complex if the rendering of the markdown is different. The difference in rendering is already a source of frustration for some and presents a real barrier to opening up. This is also why in the theme all of the content blocks actually a stylesheet that aligns as much with the way GitHub renders Markdown in it's web interface.

Personally, I'd make this change only if it's clear where it makes contributing potentially more difficult (which could be nowhere, or everywhere) and if we can provide the right education for those who're dependent on the system.

This could be a tiny change with no costs or it could cause people to be unable to do their work effectively in the open. I don't have the right insight to make a good cost/benefit judgement.

I would recommend looking at the Standard for Public Code as well for an example of how we generate a beautiful and detailed artifact (in that case a PDF, from [this HTML](standard.publiccode.net/print.html)) from the same content as a `jekyll-theme` website.

Thanks

**Comment by bvhme** [comment]
Oh, and also I forgot to mention that whilst not that much work it does add some complexity to the build system, which then also needs to be maintained. The current setup actively tries to minimize maintenance work in order to aid sustainability, so we don't need to have that responsibility anywhere in the organization.

**Comment by angelplasma** [comment]
Fair and predictable points. Additional maintenance/complexity is ungreat, if arguably worthwhile—However, on further research, it seems likely there would be at least minor changes to rendering, which by itself makes this untenable.

Alright - looks like we'll be going the HTML route. Thank you for taking the time, Boris!

**Comment by bvhme** [comment]
You could also use a separate repository for the annual report, since the information will be unlikely to be updated, so maintainability of the annual report is not as heavy weighing.
